version: '3'
services:
  client:
    image: client
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: client
    env_file:
      - .env.development
    volumes:
      - /tmp/client/npm-cache:/root/.npm:z
      - ./client/src:/app/src:z
    ports:
      - "3000:80"
    environment:
      - PORT=80
    restart: "no"